services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  arcadedb:
    image: arcadedata/arcadedb:26.3.2
    ports:
      - "2480:2480"
      - "2424:2424"
      - "5432:5432"
    environment:
      - JAVA_OPTS=-Darcadedb.server.rootPassword=arcadedb -Darcadedb.server.plugins=Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
